
#if DIMENSIONAL_ANALYSIS
    global using Demo.UnitsOfMeasurement;
    global using static Demo.UnitsOfMeasurement.Math;
#else
    global using Meter = System.Double;
    global using Centimeter = System.Double;
    global using Millimeter = System.Double;
    global using Kilometer = System.Double;
    global using Inch = System.Double;
    global using Foot = System.Double;
    global using Yard = System.Double;
    global using Mile = System.Double;
    global using Second = System.Double;
    global using Minute = System.Double;
    global using Hour = System.Double;
    global using Kilogram = System.Double;
    global using Gram = System.Double;
    global using Tonne = System.Double;
    global using Pound = System.Double;
    global using Ounce = System.Double;
    global using DegKelvin = System.Double;
    global using DegCelsius = System.Double;
    global using DegRankine = System.Double;
    global using DegFahrenheit = System.Double;
    global using Ampere = System.Double;
    global using Mole = System.Double;
    global using Candela = System.Double;
    global using EUR = System.Decimal;
    global using USD = System.Decimal;
    global using GBP = System.Decimal;
    global using PLN = System.Decimal;
    global using Radian = System.Double;
    global using Degree = System.Double;
    global using Grad = System.Double;
    global using Turn = System.Double;
    global using Hertz = System.Double;
    global using Event_Hour = System.Double;
    global using Radian_Sec = System.Double;
    global using Degree_Sec = System.Double;
    global using RPM = System.Double;
    global using Meter2 = System.Double;
    global using Meter3 = System.Double;
    global using Meter_Sec = System.Double;
    global using Centimeter_Sec = System.Double;
    global using Kilometer_Hour = System.Double;
    global using MPH = System.Double;
    global using Meter_Sec2 = System.Double;
    global using Newton = System.Double;
    global using PoundForce = System.Double;
    global using Poundal = System.Double;
    global using Dyne = System.Double;
    global using Joule = System.Double;
    global using Watt = System.Double;
    global using NewtonMeter = System.Double;
    global using Joule_Kelvin = System.Double;
    global using Joule_Kelvin_Kilogram = System.Double;
    global using Pascal = System.Double;
    global using Bar = System.Double;
    global using AtmTechnical = System.Double;
    global using AtmStandard = System.Double;
    global using MillimeterHg = System.Double;
    global using Coulomb = System.Double;
    global using Volt = System.Double;
    global using Ohm = System.Double;
    global using Siemens = System.Double;
    global using Farad = System.Double;
    global using Weber = System.Double;
    global using Meter2_Sec2 = System.Double;
    global using Kelvin = System.Double;
    global using Celsius = System.Double;
    global using Rankine = System.Double;
    global using Fahrenheit = System.Double;
    global using static System.Math;
#endif
  